export const REFLECTIONS = [
  "The bridge did not need to reach farther. It needed to turn.",
  "A little weight, placed carefully, can change your horizon.",
  "Two turns made a route that neither could make alone.",
  "The resting place between bridges is part of the journey.",
  "First find the height. Then find the direction.",
  "Each landing gives the next climb a beginning.",
  "Going around brought you somewhere new.",
  "The route held together one connection at a time.",
  "A winding path still has a clear destination.",
  "The gap changed when you changed your height.",
  "Every junction asks you to look again.",
  "You passed this place before, but never from here.",
  "What seemed distant became a sequence of small decisions.",
  "A change in direction need not be a change in purpose.",
  "There is room to stand between one effort and the next.",
  "You returned to a familiar line at a different height.",
  "The crossing was waiting for the right arrangement.",
  "The tower is made of landings as much as climbs.",
  "The space between structures gave the bridge its purpose.",
  "Several moving parts found a shared direction.",
  "One step gave the next step somewhere to begin.",
  "The route was a relationship between pieces.",
  "From the summit, each earlier landing is still visible in memory.",
  "Two distant places can share a single outline.",
  "The new height made a different reading possible.",
  "The last path appeared when you changed your point of view.",
];
